version: '3.9'

services:
  web:
    build:
      dockerfile: docker/Dockerfile.local
    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000"
    container_name: shop_local_web
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: shop_local_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    env_file:
      - .env.db

  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: "user@shop.com"
  #       PGADMIN_DEFAULT_PASSWORD: "User123!"
  #   ports:
  #       - "16543:80"
  #   depends_on:
  #           - db
  
  redis:
    container_name: shop_local_redis

  celery:
    build:
      dockerfile: docker/Dockerfile.local
    container_name: shop_local_celery
    env_file:
      - .env

  celery-beat:
    build:
      dockerfile: docker/Dockerfile.local
    container_name: shop_local_celery_beat
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume: