version: '3.7'

services:
  web:
    build:
      context: .
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A shop worker -B -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DEBUG=True
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - redis
      - web
    env_file:
      - .env

  celery-beat:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    command: celery -A shop worker -B -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/usr/src/app/
    depends_on:
      - db
      - redis
      - web
      - celery
    env_file:
      - .env
